AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for running My Portfolio Page on EC2.
Resources:
  WebServerHostNginx:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02e136e904f3da870
      InstanceType: t2.micro
      KeyName: temelcikey
      SecurityGroups:
        - TemelciSecGroup
      Tags:
        - Key: Name 
          Value: !Sub Web Server of  ${AWS::StackName} Stack
      UserData: 
        Fn::Base64:
          !Sub |
            #!/bin/bash
            yum update -y 
            amazon-linux-extras install nginx1 -y
            yum install pip -y
            pip install Flask -y
            pip install flask-cors -y
            yum install git -y
            FOLDER="https://raw.githubusercontent.com/isatemelci1/myportfolio-flask-app/main"
            cd /usr/share/nginx/html
            wget $FOLDER/app.py
            mkdir /static/css
            cd /static/css
            wget $FOLDER/static/css/mystyle.css
            cd ..
            wget $FOLDER/static/profile.jpg
            cd ..
            mkdir /templates && cd templates
            wget $FOLDER/templates/index.html
            systemctl start nginx
            systemctl enable nginx
Outputs:
  WebsiteURL:
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServerHostNginx.PublicDnsName
    Description: My Portfolio Page URL